### ISSUE TITLE
game.libretro addons create files in Application directory

### ISSUE THREAD

**Issue by zach-morris** [garbear/xbmc#93]
Version tested:
```
14:59:16.547 T:140735305183232  NOTICE: Starting Kodi (18.0-ALPHA1 Git:20180215-276e1a4). Platform: OS X x86 64-bit
14:59:16.548 T:140735305183232  NOTICE: Using Debug Kodi x64 build
14:59:16.548 T:140735305183232  NOTICE: Kodi compiled Feb 15 2018 by Clang 9.0.0 (clang-900.0.37) for OS X x86 64-bit version 10.8.0 (1080)
14:59:16.548 T:140735305183232  NOTICE: Running on Apple Inc. MacBookPro12,1 with OS X 10.11.6, kernel: Darwin x86 64-bit version 15.6.0
14:59:16.548 T:140735305183232  NOTICE: FFmpeg version/source: 3.4.1-Kodi
14:59:16.549 T:140735305183232  NOTICE: Host CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz, 4 cores available
```

Issue:  2048 created the following files in the application directory.  I would expect these to be saved in the userdata directory:
game.libretro.xml
game.libretro.sav

Contents of game.libretro.xml
```
<?xml version="1.0" ?>
<savestate>
    <path>game.libretro.sav</path>
    <type>auto</type>
    <label>02/17/2018 3:01:12 PM</label>
    <size>680</size>
    <gameclient>game.libretro.2048</gameclient>
    <gamepath>game.libretro.2048</gamepath>
    <gamecrc></gamecrc>
    <frames>78</frames>
    <wallclock>1.218750</wallclock>
    <timestamp>2018-02-17 15:01:12</timestamp>
    <thumbnail></thumbnail>
</savestate>
```

Associated log:
```
15:01:09.447 T:140735305183232   DEBUG: AddOnLog: 2048: Setting libretro pixel format "XRGB8888"
15:01:09.447 T:140735305183232    INFO: GAME: ---------------------------------------
15:01:09.447 T:140735305183232    INFO: GAME: Base Width:   376
15:01:09.448 T:140735305183232    INFO: GAME: Base Height:  464
15:01:09.448 T:140735305183232    INFO: GAME: Max Width:    376
15:01:09.448 T:140735305183232    INFO: GAME: Max Height:   464
15:01:09.448 T:140735305183232    INFO: GAME: Aspect Ratio: 1.000000
15:01:09.448 T:140735305183232    INFO: GAME: FPS:          60.000000
15:01:09.448 T:140735305183232    INFO: GAME: Sample Rate:  30000.000000
15:01:09.448 T:140735305183232    INFO: GAME: Region:       NTSC
15:01:09.448 T:140735305183232    INFO: GAME: ---------------------------------------
15:01:09.448 T:140735305183232   DEBUG: GAME: Correcting audio and video by 1.066667 to avoid resampling
15:01:09.448 T:140735305183232   DEBUG: GAME: Audio sample rate normalized to 32000
15:01:09.448 T:140735305183232   DEBUG: GAME: Video frame rate scaled to 64.000000
15:01:09.449 T:140735305183232    INFO: GAME: In-game saves (save ram) loaded from special://masterprofile/Savestates/InGameSaves/game.libretro.2048.sav
15:01:09.449 T:140735305183232   DEBUG: GAME: No in-game saves (rtc) to load
...
15:01:12.784 T:140735305183232   DEBUG: RetroPlayer[PLAYER]: Closing file
15:01:12.784 T:140735305183232   DEBUG: Saving savestate to game.libretro.sav
15:01:12.784 T:140735305183232   DEBUG: RetroPlayer[SAVE]: Saved state to game.libretro.sav
15:01:12.784 T:123145305063424   DEBUG: Thread GameLoop 123145305063424 terminating
15:01:12.785 T:140735305183232    INFO: GAME: In-game saves (save ram) written to special://masterprofile/Savestates/InGameSaves/game.libretro.2048.sav
15:01:12.785 T:140735305183232   DEBUG: GAME: No in-game saves (rtc) to save
15:01:12.785 T:140735305183232   DEBUG: AddOnLog: 2048: Settings port "1" (libretro port 0) to controller "" (libretro device ID 0)
15:01:12.786 T:140735305183232   DEBUG: SECTION:UnloadDll(/Applications/Kodi_Retroplayer.app/Contents/Resources/Kodi/addons/game.libretro/game.libretro.1.0.36.dylib)
15:01:12.786 T:140735305183232    INFO: ADDON: Dll Destroyed - 2048
```

Other game.libretro addons that do this:
Mr. Boom
fMSX
ScummVM

**Comment by garbear** [comment]
Addressed by https://github.com/xbmc/xbmc/pull/13990

**Comment by garbear** [comment]
Merged https://github.com/xbmc/xbmc/pull/13990. Can you verify if fixed?

**Comment by zach-morris** [comment]
Still occurring with 18.0-ALPHA2 Git:20180531-9d64395be6, which was what was packaged in kodi-20180614-cd7cabc8-retroplayer-18alpha2-x86_64.dmg - maybe there was a packing error there?

**Comment by zach-morris** [comment]
Scratch that, verified fixed in the nightly kodi-20180619-87c7f9b6-master-x86_64
